CREATE TABLE IF NOT EXISTS post_images(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id INT UNSIGNED NOT NULL UNIQUE,
  image_1 VARCHAR(255) NOT NULL,
  image_name_1 VARCHAR(255) NOT NULL,
  image_2 VARCHAR(255),
  image_name_2 VARCHAR(255) NOT NULL,
  image_3 VARCHAR(255),
  image_name_3 VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
) ENGINE=InnoDB;